name: Upload Assertio to PyPi Test

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build package
      run: python -m build

  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
